---
#- name: set selinux to enforcing
#  selinux:
#    policy: targeted
#    state: enforcing

- block:
  - name: create docker config directory
    file:
      path: /root/.docker
      state: directory
  
  - name: download docker login config.json
    copy:
      src: /root/{{ config_repo }}/image_provisioner/config.json
      dest: /root/.docker/
      remote_src: true
  
  - name: install docker
    yum:
      name: docker
      state: latest
  when: not atomic | default(False) | bool

- name: stop docker service
  systemd:
    name: docker
    state: stopped

- block:
   - name: extend root volume
     command: lvextend -l +60%FREE /dev/atomicos/root

   - name: resize the filesystem
     command: xfs_growfs /dev/atomicos/root

   - name: reset docker storage
     command: atomic storage reset
  when: atomic | default(False) | bool

- block:
   - name: format the partition
     filesystem:
       fstype: xfs
       dev: "{{ docker_storage_device }}"

   - name: set docker_storage_mount_path if empty or undefined
     set_fact:
        docker_storage_mount_path: "/var/lib/docker"
     when: ( docker_storage_mount_path == "" or docker_storage_mount_path is not defined )

   - name: update fstab
     lineinfile:
       path: /etc/fstab
       line: "{{ docker_storage_device }} {{ docker_storage_mount_path }}                    xfs   defaults        0 0"
       insertafter: EOF
  when: docker_storage_driver == "overlay2" and not atomic | default(False) | bool
  
- name: check if docker-storage already exists
  stat:
    path: /etc/sysconfig/docker-storage
  register: ds_config

- name: delete docker-storage if it still exists
  file:
    path: /etc/sysconfig/docker-storage
    state: absent
  when: ds_config.stat.exists == True

- block:
   - name: set container_root_lv_mount_path if empty or undefined
     set_fact:
        container_root_lv_mount_path: "/var/lib/docker"
     when: ( container_root_lv_mount_path == "" or container_root_lv_mount_path is not defined )

   - name: copy docker-storage-setup config
     template:
       src: etc/sysconfig/docker-storage-setup.j2
       dest: /etc/sysconfig/docker-storage-setup
       owner: root
       group: root
       mode: 0644
  when: atomic | default(False)
  

- name: copy docker-storage-setup config
  template:
    src: etc/sysconfig/docker-storage-setup-rhel.j2
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0644
  when: not atomic | default(False)

