---
- block:
    - name: create directory to store pbench results, store openshift templates for pbench
      file: 
        path: "{{ item }}"
        state: directory
      with_items:
         - /var/lib/pbench-agent
         - /var/home/openshift-templates/pbench

    - name: copy openshift template for pbench
      copy: 
        src: pbench-agent-daemonset.yml  
        dest: /var/home/openshift-templates/pbench 
        owner: root 
        group: root 
        mode: 0644
  when: atomic | default(False) | bool

##--- walid added more debugs: ---------------------
- name: DEBUG Walid added cat /etc/fstab command
  command: cat /etc/fstab

- name: DEBUG Walid added lsblk command
  command: lsblk

- name: DEBUG Walid added mount command
  command: mount

- name: DEBUG Walid added findmnt command
  command: findmnt
##-----------------------------------------
     
# not using docker_image module of ansible since that requires docker-py package to be installed on the atomic host
- name: pull pbench-agent from dockerhub
  command: docker pull ravielluri/image:agent

- name: tag pbench-agent image
  command: docker tag ravielluri/image:agent library/pbench-agent:latest

- name: pull pbench-controller image from dockerhub
  command: docker pull ravielluri/image:controller

- name: tag pbench-controller image
  command: docker tag ravielluri/image:controller pbench-controller:latest
