---
- name: install openshift packages with openvswitch from rhel7-fast-datapath-rpms by disabling rhel7-fast-datapath-htb repo 
  yum: 
    name: "{{ item }}"
    state: latest
    disablerepo: rhel7-fast-datapath-htb
  with_items:
    - atomic-openshift-sdn-ovs
    - atomic-openshift-tests
    - atomic-openshift-node
    - atomic-openshift-pod
## on 3.10.0-0.20.0 puddle, package "atomic-openshift-utils" was removed from puddle repo aos.repo:
## https://github.com/openshift/openshift-ansible/blob/master/openshift-ansible.spec#L188
##    - atomic-openshift-utils
## replacing it with atomic-openshift pkg
    - atomic-openshift
    - atomic-openshift-clients
    - atomic-openshift-clients-redistributable
    - atomic-openshift-dockerregistry
    - tuned-profiles-atomic
    - tuned-profiles-atomic-openshift-node
    - atomic-openshift-docker-excluder
    - atomic-openshift-excluder

